### ISSUE TITLE
Fix Social Media Links 

### ISSUE THREAD

**Issue by Wild1145** [AtlasMediaGroup/Website#2]
All the social media links need to be fixed...

**Comment by Tozzit** [comment]
they look completely fine to me?

**Comment by nullbyte-ui** [comment]
> they look completely fine to me?

Pretty sure Seth only has access to most of those social media accounts, believe they're no longer apart of TF since we can't access them.

**Comment by Wild1145** [comment]
I think the issue with most of this is less with what's in Github and more with what's currently live. I ended up needing to make a load of changes to the site to get it hosted and killed most of the social links. I need to complete #1 and then hopefully this will be sort of solved but wanted to make sure it was tracked so we can ensure all the links we use are proper and official.

**Comment by Wild1145** [comment]
The site is going to be re-written so this is no longer valid.
